In [1]:
import numpy as np


In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [7]:
arr1.shape #row and column

(2, 3)

In [8]:
arr1.size

6

In [16]:
np.zeros((2,6)) # create matrix of 2,3 having zeros value

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((2,3)) # dot is here because number is float

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.zeros((2,6),dtype = int) 

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [22]:
arr3 = np.arange(1,10,3) # here arange take three parameter in which
# first number is start and second is last element where third help in increase with value
print(arr3)

[1 4 7]


In [26]:
sample_matrix = np.array([np.arange(1,10,2),np.arange(1,10,2)])
print(sample_matrix)

[[1 3 5 7 9]
 [1 3 5 7 9]]


In [27]:
print(sample_matrix* sample_matrix)

[[ 1  9 25 49 81]
 [ 1  9 25 49 81]]


In [28]:
print(sample_matrix**2)

[[ 1  9 25 49 81]
 [ 1  9 25 49 81]]


In [32]:
purchase = np.array([
    [200,30,45],
    [200,30,45],
    [200,30,45],
    [200,30,45]
])

total_spent= purchase.sum(axis = 1)

In [33]:
print(total_spent)


[275 275 275 275]


In [34]:
average_spent = purchase.mean(axis = 1)

In [40]:
print(average_spent)


[91.66666667 91.66666667 91.66666667 91.66666667]


In [47]:
# 2x + 3y = 8
# 4x + y = 10
a = np.array([[2,3],[4,1]])
b = np.array([8,10])

solution = np.linalg.solve(a,b)

print(f"solution (x,y): {solution}")

solution (x,y): [2.2 1.2]


In [50]:
sales = np.array([10,20,320,101,12,20,487236,456,434,434])
total_sum = sales.sum()
print(total_sum)

489043


In [51]:
avg_sum = total_sum / len(sales)
print(avg_sum)

48904.3


In [52]:
high_sale = sales.max()
lowest_sale = sales.min()

print(f"highest : {high_sale}  and lowest : {lowest_sale}")

highest : 487236  and lowest : 10


In [55]:
for i  in sales : 
    if i > avg_sum:
        print(f"this is value greater than avg: {i}")
        

this is value greater than avg: 487236


In [62]:
print(sales[sales >avg_sum])

[487236]


In [63]:
updated = sales * 1.1
new_sales = np.array(updated)

print(new_sales)

[1.100000e+01 1.320000e+01 2.200000e+01 2.200000e+01 1.111000e+02
 3.520000e+02 4.774000e+02 4.774000e+02 5.016000e+02 5.359596e+05]


In [58]:
sales.sort()

In [59]:
print(sales)

[    10     12     20     20    101    320    434    434    456 487236]
